### ISSUE TITLE
Not work in parcel 2.0.1

### ISSUE THREAD

**Issue by Nikolasgrizli** [Epimodev/parcel-plugin-svg-sprite#27]
Hello, you made a very useful plugin, but unfortunately it doesn't work for me - I'm trying Parcel as an alternative to webpack project builder and I like it, but there are one BUT that I still can't beat (here are links to starting builds - [build on Parcel](https://github.com/Nikolasgrizli/Starter-parcel) and [build on webpack](https://github.com/Nikolasgrizli/Starter-webpack5-/tree/onelang)):
In the assembly under the webpack, I used svg-sprite-loader to create svg sprites, which adds immediately after opening body svg with symbols like this:
`<svg>
<symbol ...>
<symbol ...>
`
and your plugin, judging by the description, should also work in a similar way, but it doesn't work for me.
I tried to configure the plugin both through the package.json and through a separate settings file, I also tried to run the project simply on html (I use a pug in the assembly), but unfortunately this did not work either ((
As a result, for now, I am inserting svg in the way described in the parcel documentation (I use a pug in the project):
```
svg
   use (href = "../../icons/facebook.svg")
```
but in this case, I only get an empty space, although when i click on the link in svg, the correct svg file opens((

**Comment by Epimodev** [comment]
Hello @Nikolasgrizli 

As I'm using [vite](https://github.com/vitejs/vite) for 1 year, I didn't plan to adapt this plugin for Parcel 2. So I think it doesn't work because there was a lot of changes since Parcel 1.

I will try to adapt this plugin for Parcel 2 during next days. I will keep you informed :-)

**Comment by Nikolasgrizli** [comment]
> Hello @Nikolasgrizli
> 
> As I'm using [vite](https://github.com/vitejs/vite) for 1 year, I didn't plan to adapt this plugin for Parcel 2. So I think it doesn't work because there was a lot of changes since Parcel 1.
> 
> I will try to adapt this plugin for Parcel 2 during next days. I will keep you informed :-)

Thank you, I will look forward to it!

**Comment by Nikolasgrizli** [comment]
Hi, @Epimodev, do you have any news?

**Comment by Epimodev** [comment]
Hi @Nikolasgrizli  thanks for this reminder :-)

I tried during a few hours to create a plugin for Parcel 2 and I failed to just create a "hello world" in my local env.
I followed explanation from the [documentation](https://parceljs.org/features/plugins/#the-link%3A-protocol) and try the command "yarn link" but nothing works: I've got an error telling me that parcel don't find my package.  

So I created an [issue](https://github.com/parcel-bundler/parcel/issues/7341) in Parcel project to ask help.

I hope to find a solution soon and tell you if I can adapt this plugin for Parcel 2.

**Comment by Nikolasgrizli** [comment]
Hi, @Epimodev, I see you on the link to the issue was it possible to solve it, or are there any other problems?

**Comment by Epimodev** [comment]
Hi @Nikolasgrizli 

I worked some hours on this today and I just succeed to create a first version working with Parcel 2. So I can confirm this plugin is adaptable.

I still have to make my code more readable, add some optimizations and update the documentation.

I plan to work on this tomorrow, and I'm confident to complete it and push the new version tomorrow.

**Comment by Epimodev** [comment]
Hello @Nikolasgrizli 

I just published v2.0.0 on npm. I also updated the readme with all instructions to use this new version with parcel v2.0.1.

I keep this issue open until you test it and confirm it works for you.

Sorry for the long delay this week and thank you for your patience 🙏

**Comment by Nikolasgrizli** [comment]
Hi @Epimodev , yes, you are cool! Everything works as it should, while I tested it on a demo project, but in the near future I will try it on the first small project suitable for parcel. Thank you very much, I will keep you informed if something goes wrong)

**Comment by nikoloza** [comment]
> Hello @Nikolasgrizli
> 
> As I'm using [vite](https://github.com/vitejs/vite) for 1 year, I didn't plan to adapt this plugin for Parcel 2. So I think it doesn't work because there was a lot of changes since Parcel 1.
> 
> I will try to adapt this plugin for Parcel 2 during next days. I will keep you informed :-)

Tried out Vite, which plugin do you use for spriting?

**Comment by Epimodev** [comment]
Hi @nikoloza, my projects with Vite uses only a few icons so I created sprite manually. So I didn't use any plugin for spriting.

**Comment by nikoloza** [comment]
> Hi @nikoloza, my projects with Vite uses only a few icons so I created sprite manually. So I didn't use any plugin for spriting.

Ok, thanks mate

> Hello @Nikolasgrizli
> 
> I just published v2.0.0 on npm. I also updated the readme with all instructions to use this new version with parcel v2.0.1.
> 
> I keep this issue open until you test it and confirm it works for you.
> 
> Sorry for the long delay this week and thank you for your patience 🙏

Basically, I could also not make it work with Parcel 2, it also ignores `svgSprite.config.js` but seems like it does not attach sprite to the body.

The output 
```
parcel-transformer-svg-sprite: 

  Error
      at Object.transform (/Users/-/node_modules/parcel-transformer-svg-sprite/src/index.js:28:49)
      at async Transformation.runTransformer (/Users/-/node_modules/@parcel/core/lib/Transformation.js:653:5)
      at async Transformation.runPipeline (/Users/-/node_modules/@parcel/core/lib/Transformation.js:402:36)
      at async Transformation.runPipelines (/Users/-/node_modules/@parcel/core/lib/Transformation.js:265:40)
      at async Transformation.run (/Users/-/node_modules/@parcel/core/lib/Transformation.js:183:21)
      at async Child.handleRequest (/Users/-/node_modules/@parcel/workers/lib/child.js:216:9)

```

**Comment by jerzylets** [comment]
Same problem, svg sprite do not appear in generated html file.
